### ISSUE TITLE
Only first line of commit messages is displayed

### ISSUE THREAD

**Issue by uglycoal** [Retr0-01/better-discord-notification#1]
If you write a multiple line commit message (for listing few things in commit) only first line is displayed.

Is this intended? Is it possible to display whole commit message instead?

**Comment by uglycoal** [comment]
Additional info: 
```
Testing lines. \n Does this work?

Is this text displayed?
And this?
And this maybe?
```
This, as a commit message (a-ka Name and Description on Github (they actually get condensed into a single NOT divided text chunk)) will only display first line. Line break symbol `\n` works as a half measure to display it propely in Discord, but other lines are skipped

**Comment by Retr0-01** [comment]
Yes this is intended. Whilte testing for some reason a commit that includes newlines, in other words includes a description will not be shown properly on the final Discord embed so i decided to strip a commit's description and leave only the main text.
